// <auto-generated />
using System;
using DesafioPagueVeloz.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DesafioPagueVeloz.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20190930050540_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DesafioPagueVeloz.DAL.Models.Empresa", b =>
                {
                    b.Property<string>("CNPJ")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("NomeFantasia")
                        .IsRequired();

                    b.Property<string>("UF")
                        .IsRequired();

                    b.HasKey("CNPJ");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("DesafioPagueVeloz.DAL.Models.Fornecedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataCadastro");

                    b.Property<DateTime?>("DataNascimento");

                    b.Property<string>("Documento")
                        .IsRequired();

                    b.Property<string>("EmpresaCNPJ")
                        .IsRequired();

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.Property<string>("RG");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaCNPJ");

                    b.ToTable("Fornecedores");
                });

            modelBuilder.Entity("DesafioPagueVeloz.DAL.Models.Telefone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FornecedorId");

                    b.Property<string>("NumeroTelefone")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("FornecedorId");

                    b.ToTable("Telefones");
                });

            modelBuilder.Entity("DesafioPagueVeloz.DAL.Models.Fornecedor", b =>
                {
                    b.HasOne("DesafioPagueVeloz.DAL.Models.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaCNPJ")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DesafioPagueVeloz.DAL.Models.Telefone", b =>
                {
                    b.HasOne("DesafioPagueVeloz.DAL.Models.Fornecedor")
                        .WithMany("Telefones")
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
